version: "3"

services:
  # Prometheus service
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    restart: always

  # Grafana service
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    depends_on:
      - prom-server

  # Loki service
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    restart: always

